// Banco de dados de exercícios — movimentos com variações; frações de envolvimento muscular somam ~1.
// ponytail: frações são heurísticas de literatura de treino, não EMG; ajuste fino é do modelo de recuperação, não daqui.

const MUSCULOS = [
  { id: 'peito',        nome: 'Peitoral' },
  { id: 'costas',       nome: 'Costas (dorsais)' },
  { id: 'trapezio',     nome: 'Trapézio' },
  { id: 'ombros',       nome: 'Ombros (deltoides)' },
  { id: 'biceps',       nome: 'Bíceps' },
  { id: 'triceps',      nome: 'Tríceps' },
  { id: 'antebraco',    nome: 'Antebraço' },
  { id: 'abdomen',      nome: 'Abdômen' },
  { id: 'lombar',       nome: 'Lombar' },
  { id: 'gluteos',      nome: 'Glúteos' },
  { id: 'quadriceps',   nome: 'Quadríceps' },
  { id: 'posteriores',  nome: 'Posteriores de coxa' },
  { id: 'adutores',     nome: 'Adutores' },
  { id: 'panturrilha',  nome: 'Panturrilha' },
];

// Mapa corporal 2D — coordenadas num espaço 0–200 (largura) × 0–330 (altura) por vista.
// `esp: true` = a forma é desenhada também espelhada no eixo x=100. `m: null` = parte neutra (não rastreada).
const CORPO_SVG = {
  f: [ // vista frontal
    { m: null, forma: ['ellipse', { cx: 100, cy: 20, rx: 13, ry: 15 }] },                    // cabeça
    { m: null, forma: ['rect', { x: 92, y: 32, width: 16, height: 12, rx: 4 }] },            // pescoço
    { m: 'trapezio', esp: true, forma: ['path', { d: 'M92,36 L62,50 L92,52 Z' }] },
    { m: 'ombros', esp: true, forma: ['ellipse', { cx: 63, cy: 58, rx: 11, ry: 10 }] },
    { m: 'peito', esp: true, forma: ['path', { d: 'M97,50 C80,51 70,58 69,68 C69,79 81,85 97,84 Z' }] },
    { m: 'abdomen', forma: ['rect', { x: 86, y: 88, width: 28, height: 50, rx: 9 }] },
    { m: 'biceps', esp: true, forma: ['ellipse', { cx: 58, cy: 86, rx: 8, ry: 16 }] },
    { m: 'antebraco', esp: true, forma: ['ellipse', { cx: 51, cy: 122, rx: 6.5, ry: 17 }] },
    { m: null, esp: true, forma: ['ellipse', { cx: 47, cy: 150, rx: 5.5, ry: 7 }] },         // mão
    { m: null, forma: ['rect', { x: 82, y: 142, width: 36, height: 16, rx: 6 }] },           // pelve
    { m: 'quadriceps', esp: true, forma: ['rect', { x: 76, y: 158, width: 20, height: 62, rx: 10 }] },
    { m: 'adutores', forma: ['rect', { x: 96.5, y: 158, width: 7, height: 34, rx: 3.5 }] },
    { m: null, esp: true, forma: ['ellipse', { cx: 86, cy: 228, rx: 6.5, ry: 6.5 }] },       // joelho
    { m: null, esp: true, forma: ['rect', { x: 79, y: 236, width: 14, height: 56, rx: 7 }] },// canela
    { m: null, esp: true, forma: ['ellipse', { cx: 85, cy: 300, rx: 8, ry: 5.5 }] },         // pé
  ],
  c: [ // vista posterior
    { m: null, forma: ['ellipse', { cx: 100, cy: 20, rx: 13, ry: 15 }] },
    { m: null, forma: ['rect', { x: 92, y: 32, width: 16, height: 12, rx: 4 }] },
    { m: 'costas', esp: true, forma: ['path', { d: 'M97,64 C80,68 68,78 67,92 C67,108 80,120 97,124 Z' }] },
    { m: 'trapezio', forma: ['path', { d: 'M100,36 L128,52 L100,84 L72,52 Z' }] },
    { m: 'ombros', esp: true, forma: ['ellipse', { cx: 63, cy: 58, rx: 11, ry: 10 }] },
    { m: 'lombar', forma: ['rect', { x: 89, y: 124, width: 22, height: 30, rx: 6 }] },
    { m: 'triceps', esp: true, forma: ['ellipse', { cx: 58, cy: 86, rx: 8, ry: 16 }] },
    { m: 'antebraco', esp: true, forma: ['ellipse', { cx: 51, cy: 122, rx: 6.5, ry: 17 }] },
    { m: null, esp: true, forma: ['ellipse', { cx: 47, cy: 150, rx: 5.5, ry: 7 }] },
    { m: 'gluteos', esp: true, forma: ['ellipse', { cx: 86.5, cy: 168, rx: 13.5, ry: 15 }] },
    { m: 'posteriores', esp: true, forma: ['rect', { x: 76, y: 188, width: 20, height: 52, rx: 10 }] },
    { m: null, esp: true, forma: ['ellipse', { cx: 86, cy: 247, rx: 6, ry: 6 }] },           // joelho
    { m: 'panturrilha', esp: true, forma: ['ellipse', { cx: 86, cy: 272, rx: 9.5, ry: 20 }] },
    { m: null, esp: true, forma: ['ellipse', { cx: 85, cy: 300, rx: 8, ry: 5.5 }] },
  ],
};

// Regiões de treino (splits clássicos) — usadas para detectar a sessão em andamento e sugerir o que falta
const REGIOES = [
  { id: 'empurrar', nome: 'Empurrar (peito, ombros, tríceps)', musculos: ['peito', 'ombros', 'triceps'] },
  { id: 'puxar',    nome: 'Puxar (costas, bíceps)',            musculos: ['costas', 'trapezio', 'biceps', 'antebraco'] },
  { id: 'pernas',   nome: 'Pernas',                            musculos: ['quadriceps', 'posteriores', 'gluteos', 'adutores', 'panturrilha'] },
  { id: 'core',     nome: 'Core',                              musculos: ['abdomen', 'lombar'] },
];

// Animações ilustrativas — boneco palito em vista lateral, espaço 0–100.
// Juntas: ca(beça) om(bro) co(tovelo) mã(o) qu(adril) jo(elho) pé. Poses A→B em vai-e-vem.
// peso: círculo na mão (ou em pesoEm); banco: [x,y,w,h]; chao/topo/linha/ancora: cenário.
const ANIMS = {
  press:      { peso: 1, banco: [20, 66, 44, 5],
    A: { ca: [24, 59], om: [33, 62], co: [27, 70], ma: [36, 52], qu: [54, 62], jo: [63, 72], pe: [65, 86] },
    B: { ca: [24, 59], om: [33, 62], co: [33, 50], ma: [35, 38], qu: [54, 62], jo: [63, 72], pe: [65, 86] } },
  desenv:     { peso: 1, chao: 88,
    A: { ca: [50, 23], om: [50, 34], co: [57, 42], ma: [56, 30], qu: [50, 58], jo: [51, 73], pe: [50, 88] },
    B: { ca: [50, 23], om: [50, 34], co: [54, 20], ma: [52, 10], qu: [50, 58], jo: [51, 73], pe: [50, 88] } },
  elevacao:   { peso: 1, chao: 88,
    A: { ca: [50, 23], om: [50, 34], co: [52, 44], ma: [53, 55], qu: [50, 58], jo: [51, 73], pe: [50, 88] },
    B: { ca: [50, 23], om: [50, 34], co: [59, 36], ma: [68, 33], qu: [50, 58], jo: [51, 73], pe: [50, 88] } },
  rosca:      { peso: 1, chao: 88,
    A: { ca: [50, 23], om: [50, 34], co: [53, 45], ma: [55, 57], qu: [50, 58], jo: [51, 73], pe: [50, 88] },
    B: { ca: [50, 23], om: [50, 34], co: [53, 45], ma: [58, 33], qu: [50, 58], jo: [51, 73], pe: [50, 88] } },
  triceps:    { peso: 1, ancora: [68, 6], chao: 88,
    A: { ca: [51, 24], om: [50, 35], co: [55, 44], ma: [61, 35], qu: [49, 58], jo: [50, 73], pe: [50, 88] },
    B: { ca: [51, 24], om: [50, 35], co: [55, 44], ma: [63, 58], qu: [49, 58], jo: [50, 73], pe: [50, 88] } },
  puxada:     { peso: 1, ancora: [64, 4], banco: [42, 72, 16, 4],
    A: { ca: [47, 28], om: [47, 40], co: [53, 26], ma: [58, 13], qu: [48, 68], jo: [60, 72], pe: [61, 86] },
    B: { ca: [47, 28], om: [47, 40], co: [50, 48], ma: [57, 38], qu: [48, 68], jo: [60, 72], pe: [61, 86] } },
  remada:     { peso: 1, chao: 88,
    A: { ca: [68, 33], om: [60, 39], co: [63, 49], ma: [65, 60], qu: [44, 57], jo: [49, 71], pe: [50, 88] },
    B: { ca: [68, 33], om: [60, 39], co: [56, 52], ma: [59, 46], qu: [44, 57], jo: [49, 71], pe: [50, 88] } },
  remada_alta:{ peso: 1, chao: 88,
    A: { ca: [50, 23], om: [50, 34], co: [52, 46], ma: [53, 57], qu: [50, 58], jo: [51, 73], pe: [50, 88] },
    B: { ca: [50, 23], om: [50, 34], co: [60, 38], ma: [54, 33], qu: [50, 58], jo: [51, 73], pe: [50, 88] } },
  hinge:      { peso: 1, chao: 88,
    A: { ca: [64, 36], om: [57, 42], co: [59, 52], ma: [60, 63], qu: [42, 58], jo: [48, 71], pe: [50, 88] },
    B: { ca: [50, 23], om: [50, 34], co: [51, 46], ma: [52, 58], qu: [49, 57], jo: [50, 72], pe: [50, 88] } },
  agacha:     { peso: 1, chao: 88,
    A: { ca: [50, 23], om: [50, 34], co: [55, 40], ma: [52, 32], qu: [50, 58], jo: [51, 73], pe: [50, 88] },
    B: { ca: [49, 35], om: [47, 46], co: [52, 50], ma: [49, 44], qu: [43, 68], jo: [57, 72], pe: [50, 88] } },
  afundo:     { peso: 1, chao: 88,
    A: { ca: [50, 23], om: [50, 34], co: [52, 45], ma: [53, 56], qu: [50, 58], jo: [51, 73], pe: [50, 88] },
    B: { ca: [49, 29], om: [48, 40], co: [50, 50], ma: [51, 61], qu: [47, 66], jo: [59, 73], pe: [59, 87] } },
  legpress:   { linha: [66, 34, 80, 54],
    A: { ca: [25, 42], om: [30, 50], co: [36, 60], ma: [43, 64], qu: [42, 64], jo: [50, 50], pe: [62, 42] },
    B: { ca: [25, 42], om: [30, 50], co: [36, 60], ma: [43, 64], qu: [42, 64], jo: [55, 54], pe: [73, 48] } },
  extensora:  { banco: [40, 66, 18, 4],
    A: { ca: [46, 25], om: [46, 36], co: [49, 52], ma: [52, 63], qu: [48, 62], jo: [59, 64], pe: [59, 80] },
    B: { ca: [46, 25], om: [46, 36], co: [49, 52], ma: [52, 63], qu: [48, 62], jo: [59, 64], pe: [75, 62] } },
  flexora:    { banco: [20, 64, 46, 5],
    A: { ca: [25, 58], om: [32, 61], co: [28, 68], ma: [25, 74], qu: [52, 62], jo: [62, 62], pe: [76, 60] },
    B: { ca: [25, 58], om: [32, 61], co: [28, 68], ma: [25, 74], qu: [52, 62], jo: [62, 62], pe: [68, 42] } },
  hipthrust:  { peso: 1, pesoEm: 'qu', banco: [16, 52, 14, 18], chao: 88,
    A: { ca: [22, 46], om: [28, 55], co: [33, 60], ma: [38, 63], qu: [44, 70], jo: [58, 62], pe: [59, 84] },
    B: { ca: [22, 46], om: [28, 55], co: [33, 60], ma: [38, 63], qu: [45, 55], jo: [58, 58], pe: [59, 84] } },
  panturrilha:{ peso: 1, chao: 88,
    A: { ca: [50, 23], om: [50, 34], co: [52, 45], ma: [53, 56], qu: [50, 58], jo: [51, 73], pe: [50, 88] },
    B: { ca: [50, 19], om: [50, 30], co: [52, 41], ma: [53, 52], qu: [50, 54], jo: [51, 69], pe: [50, 84] } },
  crunch:     { chao: 70,
    A: { ca: [25, 63], om: [32, 66], co: [33, 62], ma: [27, 60], qu: [48, 66], jo: [59, 54], pe: [66, 68] },
    B: { ca: [32, 53], om: [37, 58], co: [38, 54], ma: [32, 50], qu: [48, 66], jo: [59, 54], pe: [66, 68] } },
  legraise:   { chao: 70,
    A: { ca: [24, 64], om: [31, 66], co: [38, 68], ma: [44, 68], qu: [50, 66], jo: [61, 66], pe: [73, 66] },
    B: { ca: [24, 64], om: [31, 66], co: [38, 68], ma: [44, 68], qu: [50, 66], jo: [57, 50], pe: [63, 36] } },
  prancha:    { chao: 70,
    A: { ca: [24, 53], om: [31, 55], co: [29, 66], ma: [38, 66], qu: [50, 58], jo: [61, 62], pe: [72, 67] },
    B: { ca: [24, 52], om: [31, 54], co: [29, 66], ma: [38, 66], qu: [50, 56], jo: [61, 61], pe: [72, 67] } },
  encolhe:    { peso: 1, chao: 88,
    A: { ca: [50, 23], om: [50, 34], co: [52, 46], ma: [53, 57], qu: [50, 58], jo: [51, 73], pe: [50, 88] },
    B: { ca: [50, 22], om: [50, 29], co: [52, 42], ma: [53, 53], qu: [50, 58], jo: [51, 73], pe: [50, 88] } },
  barrafixa:  { topo: 1,
    A: { ca: [46, 28], om: [50, 34], co: [50, 22], ma: [50, 10], qu: [50, 57], jo: [53, 70], pe: [54, 82] },
    B: { ca: [47, 13], om: [50, 21], co: [55, 18], ma: [50, 10], qu: [50, 44], jo: [55, 56], pe: [56, 68] } },
  flexao:     { chao: 88,
    A: { ca: [20, 78], om: [29, 80], co: [24, 85], ma: [32, 87], qu: [51, 78], jo: [62, 80], pe: [75, 86] },
    B: { ca: [19, 66], om: [28, 70], co: [26, 79], ma: [32, 87], qu: [51, 72], jo: [62, 76], pe: [75, 86] } },
  // vista frontal: braço reaproveitado como segunda perna (abre/fecha)
  abducao:    { chao: 88,
    A: { ca: [50, 26], om: [50, 38], co: [46, 70], ma: [45, 85], qu: [50, 56], jo: [54, 70], pe: [55, 85] },
    B: { ca: [50, 26], om: [50, 38], co: [39, 68], ma: [36, 82], qu: [50, 56], jo: [61, 68], pe: [64, 82] } },
};
ANIMS.aducao = { chao: 88, A: ANIMS.abducao.B, B: ANIMS.abducao.A };


// Partes dos músculos para mostrar *onde* o exercício trabalha (ex.: deltoide lateral vs. posterior).
// Cada peça redesenha o músculo do mapa corporal recortado pelo retângulo r = [x, y, largura, altura]
// (lado esquerdo da figura; o recorte é espelhado sozinho). Sem r = músculo inteiro naquela vista.
// A 1ª peça define o músculo "dono" da parte (usado no texto de foco/auxiliares).
const PARTES = {
  delt_ant:       { nome: 'Deltoide anterior', info: 'frente do ombro', p: [{ m: 'ombros', v: 'f', r: [59, 46, 16, 24] }] },
  delt_lat:       { nome: 'Deltoide lateral', info: 'lado do ombro — é o que dá largura', p: [{ m: 'ombros', v: 'f', r: [50, 46, 9, 24] }, { m: 'ombros', v: 'c', r: [50, 46, 9, 24] }] },
  delt_post:      { nome: 'Deltoide posterior', info: 'parte de trás do ombro — ajuda na postura', p: [{ m: 'ombros', v: 'c', r: [59, 46, 16, 24] }] },
  peito_sup:      { nome: 'Peitoral superior', info: 'parte de cima, perto da clavícula', p: [{ m: 'peito', v: 'f', r: [66, 46, 34, 15] }] },
  peito_med:      { nome: 'Peitoral médio', info: 'o "miolo" do peito (porção esternal)', p: [{ m: 'peito', v: 'f', r: [66, 61, 34, 12] }] },
  peito_inf:      { nome: 'Peitoral inferior', info: 'parte de baixo do peito', p: [{ m: 'peito', v: 'f', r: [66, 73, 34, 14] }] },
  dorsal:         { nome: 'Dorsal', info: 'latíssimo — dá a largura das costas (formato em V)', p: [{ m: 'costas', v: 'c', r: [64, 64, 22, 62] }] },
  meio_costas:    { nome: 'Meio das costas', info: 'romboides e trapézio médio — dão espessura', p: [{ m: 'costas', v: 'c', r: [86, 64, 12, 34] }, { m: 'trapezio', v: 'c', r: [72, 58, 56, 27] }] },
  trap_sup:       { nome: 'Trapézio superior', info: 'entre o pescoço e o ombro', p: [{ m: 'trapezio', v: 'c', r: [72, 36, 56, 20] }, { m: 'trapezio', v: 'f' }] },
  biceps_longa:   { nome: 'Bíceps — cabeça longa', info: 'parte de fora do braço, forma o "pico"', p: [{ m: 'biceps', v: 'f', r: [49, 68, 9, 36] }] },
  biceps_curta:   { nome: 'Bíceps — cabeça curta', info: 'parte de dentro do braço', p: [{ m: 'biceps', v: 'f', r: [58, 68, 9, 36] }] },
  braquial:       { nome: 'Braquial e braquiorradial', info: 'abaixo do bíceps e topo do antebraço — engrossam o braço', p: [{ m: 'biceps', v: 'f', r: [48, 90, 20, 14] }, { m: 'antebraco', v: 'f', r: [43, 104, 16, 16] }] },
  triceps_longa:  { nome: 'Tríceps — cabeça longa', info: 'parte de dentro, a maior do tríceps', p: [{ m: 'triceps', v: 'c', r: [58, 68, 9, 36] }] },
  triceps_lat:    { nome: 'Tríceps — cabeça lateral', info: 'parte de fora, a "ferradura"', p: [{ m: 'triceps', v: 'c', r: [49, 68, 9, 36] }] },
  antebraco_flex: { nome: 'Flexores do antebraço', info: 'lado da palma da mão', p: [{ m: 'antebraco', v: 'f' }] },
  antebraco_ext:  { nome: 'Extensores do antebraço', info: 'lado de cima do antebraço', p: [{ m: 'antebraco', v: 'c' }] },
  gluteo_max:     { nome: 'Glúteo máximo', info: 'o glúteo principal — volume e força do quadril', p: [{ m: 'gluteos', v: 'c' }] },
  gluteo_med:     { nome: 'Glúteo médio', info: 'parte de cima e de fora do quadril', p: [{ m: 'gluteos', v: 'c', r: [72, 152, 16, 12] }] },
  gastro:         { nome: 'Gastrocnêmio', info: 'a "batata" da perna — trabalha com o joelho estendido', p: [{ m: 'panturrilha', v: 'c', r: [76, 251, 20, 22] }] },
  soleo:          { nome: 'Sóleo', info: 'por baixo do gastrocnêmio — trabalha com o joelho dobrado', p: [{ m: 'panturrilha', v: 'c', r: [76, 273, 20, 20] }] },
  abd_sup:        { nome: 'Abdômen superior', info: 'parte de cima do reto abdominal', p: [{ m: 'abdomen', v: 'f', r: [86, 88, 28, 24] }] },
  abd_inf:        { nome: 'Abdômen inferior', info: 'parte de baixo do reto abdominal', p: [{ m: 'abdomen', v: 'f', r: [86, 112, 28, 26] }] },
  obliquos:       { nome: 'Oblíquos', info: 'laterais da cintura', p: [{ m: 'abdomen', v: 'f', r: [86, 90, 7, 48] }] },
};

// Grupos da tela de treino — escolhe o grupo primeiro, depois o exercício e a variação.
// `musculos` = o que o grupo trabalha (para mostrar recuperação no botão).
const GRUPOS = [
  { id: 'Peito',  musculos: ['peito'] },
  { id: 'Costas', musculos: ['costas', 'trapezio', 'lombar'] },
  { id: 'Ombros', musculos: ['ombros'] },
  { id: 'Braços', musculos: ['biceps', 'triceps', 'antebraco'] },
  { id: 'Pernas', musculos: ['quadriceps', 'posteriores', 'gluteos', 'adutores', 'panturrilha'] },
  { id: 'Core',   musculos: ['abdomen', 'lombar'] },
];

// Movimentos e suas variações. Cada variação tem histórico próprio: 20 kg no halter ≠ 20 kg na máquina.
// ids das variações = ids antigos onde já existiam → registros anteriores continuam válidos.
// Por movimento: tipo (composto/isolado → descanso sugerido), foco (PARTES trabalhadas), anim (boneco palito), img (foto padrão),
// dicas (pontos de atenção na execução), faixa de reps (progressão dupla), seg (reps = segundos).
// Por variação: eq (equipamento → incremento de carga), img (null = sem foto fiel → boneco), musculos/foco/dica/inc opcionais.
const MOVIMENTOS = [
  // ---------- Peito ----------
  { id: 'supino_reto', cat: 'Peito', nome: 'Supino reto', tipo: 'composto', foco: ['peito_med', 'delt_ant'], anim: 'press', img: 'supino_reto',
    musculos: { peito: .60, triceps: .25, ombros: .15 },
    dicas: [
      'Escápulas juntas e para baixo (ombros "no bolso de trás") do início ao fim',
      'Pés firmes no chão e glúteos no banco; leve arco natural na lombar',
      'Cotovelos a ~45–70° do tronco — não abra a 90°',
      'Desça controlando até perto do peito, sem quicar',
    ],
    vars: [
      { id: 'supino_reto', nome: 'Barra', eq: 'barra', dica: 'Barra desce na linha do meio do peito; punhos retos, em cima dos cotovelos' },
      { id: 'supino_halteres', nome: 'Halteres', eq: 'halteres', img: 'supino_halteres', musculos: { peito: .60, triceps: .20, ombros: .20 },
        dica: 'Halteres descem ao lado do peito; na subida aproxime sem bater um no outro' },
      { id: 'supino_reto_maq', nome: 'Máquina', eq: 'maquina', img: null, dica: 'Ajuste o banco para as pegadas ficarem na linha do meio do peito' },
      { id: 'supino_reto_smith', nome: 'Smith', eq: 'smith', dica: 'Posicione o banco para a barra descer na linha do meio do peito' },
    ] },
  { id: 'supino_inclinado', cat: 'Peito', nome: 'Supino inclinado', tipo: 'composto', foco: ['peito_sup', 'delt_ant'], anim: 'press', img: 'supino_inclinado',
    musculos: { peito: .55, ombros: .25, triceps: .20 },
    dicas: [
      'Banco entre 30° e 45° — mais que isso vira exercício de ombro',
      'Escápulas juntas e peito aberto',
      'Desça até a parte alta do peito, logo abaixo da clavícula',
      'Cotovelos levemente fechados, sem abrir a 90°',
    ],
    vars: [
      { id: 'supino_inclinado_barra', nome: 'Barra', eq: 'barra' },
      { id: 'supino_inclinado', nome: 'Halteres', eq: 'halteres' },
      { id: 'supino_inclinado_maq', nome: 'Máquina', eq: 'maquina', img: null },
      { id: 'supino_inclinado_smith', nome: 'Smith', eq: 'smith' },
    ] },
  { id: 'supino_declinado', cat: 'Peito', nome: 'Supino declinado', tipo: 'composto', foco: ['peito_inf'], anim: 'press', img: 'supino_declinado',
    musculos: { peito: .65, triceps: .25, ombros: .10 },
    dicas: [
      'Prenda bem as pernas no apoio antes de tirar o peso',
      'Desça até a parte baixa do peito',
      'Escápulas juntas; amplitude controlada, sem quicar',
    ],
    vars: [
      { id: 'supino_declinado', nome: 'Barra', eq: 'barra' },
      { id: 'supino_declinado_halt', nome: 'Halteres', eq: 'halteres' },
      { id: 'supino_declinado_maq', nome: 'Máquina', eq: 'maquina', img: null },
    ] },
  { id: 'crucifixo', cat: 'Peito', nome: 'Crucifixo', tipo: 'isolado', foco: ['peito_med', 'delt_ant'], anim: 'press', img: 'crucifixo',
    musculos: { peito: .85, ombros: .15 },
    dicas: [
      'Cotovelos levemente dobrados e fixos — o movimento é no ombro',
      'Abra até sentir o peito alongar, sem passar muito da linha do tronco',
      'Feche como num abraço e aperte o peito por 1 s',
      'Ombros para trás e para baixo, peito aberto',
    ],
    vars: [
      { id: 'crucifixo', nome: 'Peck deck (máquina)', eq: 'maquina' },
      { id: 'crucifixo_halteres', nome: 'Halteres (reto)', eq: 'halteres', img: null },
      { id: 'crucifixo_inclinado', nome: 'Halteres (inclinado)', foco: ['peito_sup', 'delt_ant'], eq: 'halteres', img: null },
    ] },
  { id: 'crossover', cat: 'Peito', nome: 'Crossover (polia)', tipo: 'isolado', foco: ['peito_med'], anim: 'press', img: 'crossover',
    musculos: { peito: .85, ombros: .15 },
    dicas: [
      'Um pé à frente e tronco levemente inclinado para estabilizar',
      'Cotovelos semiflexionados e fixos',
      'Cruze as mãos à frente do corpo e segure 1 s na contração',
      'Volte devagar, sem deixar o cabo puxar o ombro para trás',
    ],
    vars: [
      { id: 'crossover', nome: 'Polia alta', foco: ['peito_inf'], eq: 'polia', dica: 'De cima para baixo: foco na parte inferior do peito' },
      { id: 'crossover_media', nome: 'Polia média', eq: 'polia' },
      { id: 'crossover_baixa', nome: 'Polia baixa', foco: ['peito_sup', 'delt_ant'], eq: 'polia', dica: 'De baixo para cima: foco na parte superior do peito' },
    ] },
  { id: 'flexao', cat: 'Peito', nome: 'Flexão de braço', tipo: 'composto', foco: ['peito_med', 'delt_ant'], anim: 'flexao', img: 'flexao',
    musculos: { peito: .55, triceps: .25, ombros: .15, abdomen: .05 },
    dicas: [
      'Corpo em linha reta da cabeça aos calcanhares — abdômen e glúteos contraídos',
      'Mãos um pouco mais abertas que os ombros, cotovelos a ~45°',
      'Desça até o peito quase tocar o chão',
      'Não deixe o quadril cair nem empinar',
    ],
    vars: [
      { id: 'flexao', nome: 'Tradicional', eq: 'corpo' },
      { id: 'flexao_joelhos', nome: 'Joelhos apoiados', eq: 'corpo' },
      { id: 'flexao_declinada', nome: 'Pés elevados', foco: ['peito_sup', 'delt_ant'], eq: 'corpo' },
      { id: 'flexao_diamante', nome: 'Mãos juntas (diamante)', eq: 'corpo', musculos: { triceps: .45, peito: .40, ombros: .15 } },
    ] },
  { id: 'paralelas', cat: 'Peito', nome: 'Mergulho (paralelas)', tipo: 'composto', foco: ['peito_inf', 'delt_ant'], anim: 'flexao', img: 'paralelas',
    musculos: { triceps: .50, peito: .35, ombros: .15 },
    dicas: [
      'Ombros para baixo, longe das orelhas',
      'Tronco inclinado à frente = mais peito; ereto = mais tríceps',
      'Desça até ~90° no cotovelo, sem forçar o ombro',
      'Suba sem travar os cotovelos com impacto',
    ],
    vars: [
      { id: 'paralelas', nome: 'Paralelas', eq: 'corpo' },
      { id: 'paralelas_maq', nome: 'Máquina (sentado)', eq: 'maquina', img: null },
      { id: 'paralelas_banco', nome: 'No banco', foco: ['delt_ant'], eq: 'corpo', img: null, musculos: { triceps: .70, peito: .15, ombros: .15 },
        dica: 'Mãos no banco atrás do corpo e costas rente ao banco' },
    ] },
  { id: 'pullover', cat: 'Peito', nome: 'Pullover', tipo: 'isolado', foco: ['dorsal', 'peito_med'], anim: 'press', img: 'pullover',
    musculos: { costas: .45, peito: .40, triceps: .15 },
    dicas: [
      'Cotovelos levemente dobrados e fixos durante todo o movimento',
      'Leve o peso para trás da cabeça até alongar, sem dor no ombro',
      'Abdômen firme — não arqueie a lombar',
      'Traga o peso até a linha do peito, não até o quadril',
    ],
    vars: [
      { id: 'pullover', nome: 'Halter', eq: 'halteres' },
      { id: 'pullover_polia', nome: 'Polia (em pé)', eq: 'polia', img: null, musculos: { costas: .65, peito: .20, triceps: .15 },
        dica: 'Braços quase estendidos: puxe a barra até as coxas contraindo as costas' },
    ] },

  // ---------- Costas ----------
  { id: 'puxada_frontal', cat: 'Costas', sub: 'Dorsais', nome: 'Puxada frontal (pulley)', tipo: 'composto', foco: ['dorsal'], anim: 'puxada', img: 'puxada_frontal',
    musculos: { costas: .65, biceps: .25, ombros: .10 },
    dicas: [
      'Peito para cima e tronco levemente inclinado para trás (~10–20°)',
      'Comece descendo os ombros, depois puxe com os cotovelos',
      'Barra até a parte alta do peito — nunca atrás da nuca',
      'Suba controlando até alongar as costas, sem soltar o peso',
    ],
    vars: [
      { id: 'puxada_frontal', nome: 'Pegada aberta', eq: 'polia' },
      { id: 'puxada_triangulo', nome: 'Triângulo', eq: 'polia' },
      { id: 'puxada_supinada', nome: 'Supinada', eq: 'polia', musculos: { costas: .55, biceps: .35, ombros: .10 } },
      { id: 'puxada_articulada', nome: 'Máquina articulada', eq: 'maquina', img: null },
    ] },
  { id: 'barra_fixa', cat: 'Costas', sub: 'Dorsais', nome: 'Barra fixa', tipo: 'composto', foco: ['dorsal'], anim: 'barrafixa', img: 'barra_fixa',
    musculos: { costas: .60, biceps: .25, antebraco: .10, abdomen: .05 },
    dicas: [
      'Comece pendurado com os braços estendidos e os ombros ativos',
      'Puxe levando os cotovelos em direção ao quadril',
      'Queixo passa da barra, sem balançar o corpo',
      'Desça controlando até estender os braços',
    ],
    vars: [
      { id: 'barra_fixa', nome: 'Pronada', eq: 'corpo' },
      { id: 'barra_fixa_supinada', nome: 'Supinada', eq: 'corpo', musculos: { costas: .50, biceps: .35, antebraco: .10, abdomen: .05 } },
      { id: 'barra_fixa_neutra', nome: 'Neutra', eq: 'corpo' },
    ] },
  { id: 'remada_curvada', cat: 'Costas', sub: 'Dorsais', nome: 'Remada curvada', tipo: 'composto', foco: ['meio_costas', 'dorsal'], anim: 'remada', img: 'remada_curvada',
    musculos: { costas: .55, biceps: .20, trapezio: .15, lombar: .10 },
    dicas: [
      'Tronco inclinado ~45° com a coluna neutra — não arredonde as costas',
      'Joelhos levemente dobrados, quadril para trás',
      'Puxe em direção ao umbigo levando os cotovelos para trás',
      'Junte as escápulas no topo e desça controlando',
    ],
    vars: [
      { id: 'remada_curvada', nome: 'Barra pronada', eq: 'barra' },
      { id: 'remada_curvada_sup', nome: 'Barra supinada', foco: ['dorsal', 'meio_costas'], eq: 'barra' },
      { id: 'remada_cavalinho', nome: 'Cavalinho (T-bar)', eq: 'maquina', img: null },
    ] },
  { id: 'remada_baixa', cat: 'Costas', sub: 'Dorsais', nome: 'Remada baixa (polia)', tipo: 'composto', foco: ['meio_costas', 'dorsal'], anim: 'remada', img: 'remada_baixa',
    musculos: { costas: .60, biceps: .25, trapezio: .15 },
    dicas: [
      'Tronco ereto, sem balançar para trás a cada repetição',
      'Puxe com os cotovelos junto ao corpo',
      'Junte as escápulas no final e segure 1 s',
      'Na volta, estenda os braços sem curvar a lombar',
    ],
    vars: [
      { id: 'remada_baixa', nome: 'Triângulo', eq: 'polia' },
      { id: 'remada_baixa_aberta', nome: 'Barra aberta', foco: ['meio_costas'], eq: 'polia', musculos: { costas: .55, trapezio: .25, biceps: .20 } },
      { id: 'remada_baixa_uni', nome: 'Unilateral', eq: 'polia' },
    ] },
  { id: 'remada_maquina', cat: 'Costas', sub: 'Dorsais', nome: 'Remada máquina', tipo: 'composto', foco: ['meio_costas', 'dorsal'], anim: 'remada', img: 'remada_maquina',
    musculos: { costas: .65, biceps: .20, trapezio: .15 },
    dicas: [
      'Ajuste o banco para as pegadas ficarem na altura do meio do peito',
      'Peito apoiado no suporte o tempo todo',
      'Puxe com os cotovelos, sem encolher os ombros',
      'Controle a volta até alongar',
    ],
    vars: [
      { id: 'remada_maquina', nome: 'Articulada', eq: 'maquina' },
      { id: 'remada_maquina_neutra', nome: 'Pegada neutra', eq: 'maquina' },
      { id: 'remada_maquina_aberta', nome: 'Pegada aberta', foco: ['meio_costas'], eq: 'maquina', musculos: { costas: .55, trapezio: .25, biceps: .20 } },
    ] },
  { id: 'serrote', cat: 'Costas', sub: 'Dorsais', nome: 'Remada unilateral (serrote)', tipo: 'composto', foco: ['dorsal', 'meio_costas'], anim: 'remada', img: 'serrote',
    musculos: { costas: .60, biceps: .20, trapezio: .10, lombar: .10 },
    dicas: [
      'Joelho e mão do mesmo lado no banco, costas paralelas ao chão',
      'Coluna neutra — não gire o tronco para puxar',
      'Puxe o peso em direção ao quadril, cotovelo junto ao corpo',
      'Desça até alongar bem as costas',
    ],
    vars: [
      { id: 'serrote', nome: 'Halter', eq: 'halteres' },
      { id: 'serrote_polia', nome: 'Polia', eq: 'polia', img: null },
    ] },
  { id: 'levantamento_terra', cat: 'Costas', sub: 'Lombar', nome: 'Levantamento terra', tipo: 'composto', foco: ['gluteo_max'], anim: 'hinge', img: 'levantamento_terra',
    musculos: { lombar: .25, gluteos: .25, posteriores: .25, costas: .10, trapezio: .10, quadriceps: .05 },
    dicas: [
      'Barra encostada na canela, sobre o meio do pé',
      'Coluna neutra do início ao fim — peito para cima, sem arredondar',
      'Empurre o chão e estenda quadril e joelhos juntos',
      'Barra rente ao corpo; no topo, não jogue o quadril à frente',
    ],
    vars: [
      { id: 'levantamento_terra', nome: 'Convencional', eq: 'barra' },
      { id: 'terra_sumo', nome: 'Sumô', eq: 'barra', musculos: { gluteos: .30, quadriceps: .20, posteriores: .20, lombar: .15, adutores: .10, trapezio: .05 },
        dica: 'Pés bem afastados com as pontas para fora; mãos por dentro dos joelhos' },
      { id: 'terra_hexagonal', nome: 'Barra hexagonal', eq: 'barra', musculos: { quadriceps: .25, gluteos: .25, posteriores: .20, lombar: .15, trapezio: .15 } },
    ] },
  { id: 'hiperextensao', cat: 'Costas', sub: 'Lombar', nome: 'Hiperextensão lombar', tipo: 'isolado', foco: ['gluteo_max'], anim: 'hinge', img: 'hiperextensao',
    musculos: { lombar: .60, gluteos: .25, posteriores: .15 },
    dicas: [
      'Apoio na altura do quadril, deixando o tronco livre para dobrar',
      'Desça dobrando no quadril, coluna neutra',
      'Suba até alinhar o corpo — não jogue a lombar para trás no topo',
      'Sem embalo',
    ],
    vars: [
      { id: 'hiperextensao', nome: 'Banco 45°', eq: 'corpo' },
      { id: 'hiperextensao_90', nome: 'Banco romano (90°)', eq: 'corpo' },
    ] },
  { id: 'encolhimento', cat: 'Costas', sub: 'Trapézio', nome: 'Encolhimento de ombros', tipo: 'isolado', foco: ['trap_sup'], anim: 'encolhe', img: 'encolhimento',
    musculos: { trapezio: .90, antebraco: .10 },
    dicas: [
      'Braços estendidos: suba os ombros em direção às orelhas',
      'Segure 1 s no topo',
      'Só sobe e desce — não gire os ombros',
      'Pescoço neutro, olhar à frente',
    ],
    vars: [
      { id: 'encolhimento', nome: 'Barra', eq: 'barra' },
      { id: 'encolhimento_halt', nome: 'Halteres', eq: 'halteres' },
      { id: 'encolhimento_maq', nome: 'Smith / máquina', eq: 'maquina' },
    ] },

  // ---------- Ombros ----------
  { id: 'desenvolvimento', cat: 'Ombros', nome: 'Desenvolvimento', tipo: 'composto', foco: ['delt_ant', 'delt_lat'], anim: 'desenv', img: 'desenvolvimento',
    musculos: { ombros: .65, triceps: .25, trapezio: .10 },
    dicas: [
      'Abdômen e glúteos contraídos — não arqueie a lombar',
      'Cotovelos levemente à frente do corpo, não abertos totalmente para o lado',
      'Empurre na vertical até quase estender os braços',
      'Desça até a altura do queixo, controlando',
    ],
    vars: [
      { id: 'desenvolvimento', nome: 'Barra (em pé)', eq: 'barra' },
      { id: 'desenv_halteres', nome: 'Halteres (sentado)', eq: 'halteres', img: null },
      { id: 'desenv_maquina', nome: 'Máquina', eq: 'maquina', img: 'desenv_maquina', musculos: { ombros: .70, triceps: .25, trapezio: .05 } },
      { id: 'desenv_arnold', nome: 'Arnold', eq: 'halteres', img: null, dica: 'Comece com as palmas viradas para você e gire durante a subida' },
    ] },
  { id: 'elevacao_lateral', cat: 'Ombros', nome: 'Elevação lateral', tipo: 'isolado', foco: ['delt_lat'], anim: 'elevacao', img: 'elevacao_lateral', faixa: [10, 15],
    musculos: { ombros: .90, trapezio: .10 },
    dicas: [
      'Cotovelos levemente dobrados — conduza o movimento pelos cotovelos',
      'Suba até a linha dos ombros; acima disso entra mais trapézio',
      'Tronco levemente inclinado à frente, sem embalo',
      'Desça devagar (2–3 s): a descida também conta',
    ],
    vars: [
      { id: 'elevacao_lateral', nome: 'Halteres', eq: 'halteres', inc: 1 },
      { id: 'elevacao_lateral_polia', nome: 'Polia (unilateral)', eq: 'polia', img: null },
      { id: 'elevacao_lateral_maq', nome: 'Máquina', eq: 'maquina', img: null },
    ] },
  { id: 'elevacao_frontal', cat: 'Ombros', nome: 'Elevação frontal', tipo: 'isolado', foco: ['delt_ant'], anim: 'elevacao', img: 'elevacao_frontal', faixa: [10, 15],
    musculos: { ombros: .90, trapezio: .10 },
    dicas: [
      'Braços quase estendidos; suba no máximo até a altura dos olhos',
      'Tronco firme — sem jogar o corpo para trás',
      'Desça controlando',
    ],
    vars: [
      { id: 'elevacao_frontal', nome: 'Halteres', eq: 'halteres', inc: 1 },
      { id: 'elevacao_frontal_anilha', nome: 'Anilha', eq: 'halteres' },
      { id: 'elevacao_frontal_polia', nome: 'Polia', eq: 'polia' },
    ] },
  { id: 'crucifixo_inverso', cat: 'Ombros', nome: 'Crucifixo inverso (posterior)', tipo: 'isolado', foco: ['delt_post', 'meio_costas'], anim: 'remada', img: 'crucifixo_inverso', faixa: [10, 15],
    musculos: { ombros: .60, costas: .20, trapezio: .20 },
    dicas: [
      'Cotovelos levemente dobrados e fixos',
      'Abra os braços para os lados pensando em afastar as mãos',
      'Não encolha os ombros',
      'Controle a volta',
    ],
    vars: [
      { id: 'crucifixo_inverso', nome: 'Halteres (inclinado)', eq: 'halteres', inc: 1 },
      { id: 'crucifixo_inverso_maq', nome: 'Peck deck invertido', eq: 'maquina', img: null },
      { id: 'crucifixo_inverso_polia', nome: 'Polia (cruzada)', eq: 'polia', img: null },
    ] },
  { id: 'face_pull', cat: 'Ombros', nome: 'Face pull', tipo: 'isolado', foco: ['delt_post', 'meio_costas'], faixa: [10, 15],
    musculos: { ombros: .55, trapezio: .30, costas: .15 },
    dicas: [
      'Polia na altura do rosto, polegares da corda apontando para trás',
      'Puxe em direção ao rosto abrindo as mãos para os lados',
      'Cotovelos altos, na linha dos ombros',
      'Termine com as mãos ao lado das orelhas e segure 1 s',
    ],
    vars: [
      { id: 'face_pull', nome: 'Corda', eq: 'polia' },
    ] },
  { id: 'remada_alta', cat: 'Ombros', nome: 'Remada alta', tipo: 'composto', foco: ['trap_sup', 'delt_lat'], anim: 'remada_alta', img: 'remada_alta',
    musculos: { trapezio: .50, ombros: .40, biceps: .10 },
    dicas: [
      'Pegada na largura dos ombros ou mais aberta (menos estresse no ombro)',
      'Suba conduzindo pelos cotovelos até a altura do peito',
      'Pare antes se sentir pinçar o ombro',
      'Peso próximo ao corpo',
    ],
    vars: [
      { id: 'remada_alta', nome: 'Barra', eq: 'barra' },
      { id: 'remada_alta_polia', nome: 'Polia', eq: 'polia' },
      { id: 'remada_alta_halt', nome: 'Halteres', eq: 'halteres' },
    ] },

  // ---------- Braços ----------
  { id: 'rosca_direta', cat: 'Braços', sub: 'Bíceps', nome: 'Rosca direta', tipo: 'isolado', anim: 'rosca', img: 'rosca_direta',
    musculos: { biceps: .80, antebraco: .20 },
    dicas: [
      'Cotovelos colados ao corpo e parados — só o antebraço se move',
      'Sem balançar o tronco para ajudar',
      'Suba até contrair o bíceps e desça até quase estender',
      'Punhos firmes, sem dobrar',
    ],
    vars: [
      { id: 'rosca_direta', nome: 'Barra reta', eq: 'barra' },
      { id: 'rosca_w', nome: 'Barra W', eq: 'barra' },
      { id: 'rosca_polia', nome: 'Polia', eq: 'polia' },
      { id: 'rosca_halteres', nome: 'Halteres (juntos)', eq: 'halteres', img: 'rosca_alternada' },
    ] },
  { id: 'rosca_alternada', cat: 'Braços', sub: 'Bíceps', nome: 'Rosca alternada', tipo: 'isolado', anim: 'rosca', img: 'rosca_alternada',
    musculos: { biceps: .80, antebraco: .20 },
    dicas: [
      'Gire o punho na subida, terminando com a palma para cima',
      'Cotovelo parado ao lado do corpo',
      'Alterne sem embalo do tronco',
      'Desça devagar até estender o braço',
    ],
    vars: [
      { id: 'rosca_alternada', nome: 'Em pé', eq: 'halteres' },
      { id: 'rosca_alternada_sent', nome: 'Sentado', eq: 'halteres' },
      { id: 'rosca_inclinada', nome: 'Banco inclinado', foco: ['biceps_longa'], eq: 'halteres', img: null, musculos: { biceps: .90, antebraco: .10 },
        dica: 'Braços pendurados atrás da linha do corpo: alonga mais o bíceps' },
    ] },
  { id: 'rosca_martelo', cat: 'Braços', sub: 'Bíceps', nome: 'Rosca martelo', tipo: 'isolado', foco: ['braquial'], anim: 'rosca', img: 'rosca_martelo',
    musculos: { biceps: .60, antebraco: .40 },
    dicas: [
      'Pegada neutra (palmas uma de frente para a outra) o tempo todo',
      'Cotovelos fixos ao lado do corpo',
      'Suba até a altura do ombro sem balançar',
    ],
    vars: [
      { id: 'rosca_martelo', nome: 'Halteres', eq: 'halteres' },
      { id: 'rosca_martelo_corda', nome: 'Polia (corda)', eq: 'polia' },
    ] },
  { id: 'rosca_scott', cat: 'Braços', sub: 'Bíceps', nome: 'Rosca Scott', tipo: 'isolado', foco: ['biceps_curta'], anim: 'rosca', img: 'rosca_scott',
    musculos: { biceps: .90, antebraco: .10 },
    dicas: [
      'Axilas encaixadas no topo do apoio, braço todo apoiado',
      'Desça até quase estender, sem "soltar" o peso no fim (protege o cotovelo)',
      'Suba sem tirar os cotovelos do apoio',
    ],
    vars: [
      { id: 'rosca_scott', nome: 'Barra W', eq: 'barra' },
      { id: 'rosca_scott_maq', nome: 'Máquina', eq: 'maquina' },
      { id: 'rosca_scott_halt', nome: 'Halter (unilateral)', eq: 'halteres' },
    ] },
  { id: 'triceps_pulley', cat: 'Braços', sub: 'Tríceps', nome: 'Tríceps na polia', tipo: 'isolado', foco: ['triceps_lat'], anim: 'triceps', img: 'triceps_pulley',
    musculos: { triceps: .95, antebraco: .05 },
    dicas: [
      'Cotovelos colados ao corpo e parados',
      'Estenda totalmente e contraia o tríceps embaixo',
      'Suba só até ~90° no cotovelo — os cotovelos não sobem junto',
      'Tronco firme, sem jogar o peso do corpo',
    ],
    vars: [
      { id: 'triceps_pulley', nome: 'Barra', eq: 'polia' },
      { id: 'triceps_corda', nome: 'Corda', eq: 'polia', dica: 'Abra a corda para os lados no final do movimento' },
      { id: 'triceps_pulley_inv', nome: 'Pegada invertida', eq: 'polia' },
      { id: 'triceps_pulley_uni', nome: 'Unilateral', eq: 'polia' },
    ] },
  { id: 'triceps_testa', cat: 'Braços', sub: 'Tríceps', nome: 'Tríceps testa', tipo: 'isolado', foco: ['triceps_longa'], anim: 'triceps', img: 'triceps_testa',
    musculos: { triceps: 1 },
    dicas: [
      'Braços apontando para o teto (ou levemente para trás)',
      'Só o cotovelo dobra — os braços não se movem',
      'Desça controlando até a testa ou o topo da cabeça',
      'Cotovelos fechados, sem abrir para os lados',
    ],
    vars: [
      { id: 'triceps_testa', nome: 'Barra W', eq: 'barra' },
      { id: 'triceps_testa_halt', nome: 'Halteres', eq: 'halteres' },
      { id: 'triceps_testa_polia', nome: 'Polia', eq: 'polia' },
    ] },
  { id: 'triceps_frances', cat: 'Braços', sub: 'Tríceps', nome: 'Tríceps francês', tipo: 'isolado', foco: ['triceps_longa'], anim: 'triceps', img: 'triceps_frances',
    musculos: { triceps: 1 },
    dicas: [
      'Cotovelos apontando para cima, perto da cabeça',
      'Desça atrás da cabeça até alongar bem o tríceps',
      'Abdômen contraído, sem arquear a lombar',
      'Estenda sem mexer os braços',
    ],
    vars: [
      { id: 'triceps_frances', nome: 'Halter (sentado)', eq: 'halteres' },
      { id: 'triceps_frances_polia', nome: 'Polia', foco: ['triceps_longa'], eq: 'polia' },
      { id: 'triceps_frances_uni', nome: 'Unilateral', eq: 'halteres' },
    ] },
  { id: 'rosca_punho', cat: 'Braços', sub: 'Antebraço', nome: 'Rosca de punho', tipo: 'isolado', foco: ['antebraco_flex'], anim: 'rosca', img: 'rosca_punho', faixa: [12, 20],
    musculos: { antebraco: 1 },
    dicas: [
      'Antebraços apoiados — só o punho se move',
      'Amplitude completa: deixe a barra rolar até os dedos',
      'Carga leve e movimento controlado',
    ],
    vars: [
      { id: 'rosca_punho', nome: 'Flexão (palmas para cima)', eq: 'barra' },
      { id: 'rosca_punho_inv', nome: 'Extensão (palmas para baixo)', foco: ['antebraco_ext'], eq: 'barra' },
    ] },

  // ---------- Pernas ----------
  { id: 'agachamento', cat: 'Pernas', sub: 'Quadríceps', nome: 'Agachamento', tipo: 'composto', foco: ['gluteo_max'], anim: 'agacha', img: 'agachamento',
    musculos: { quadriceps: .45, gluteos: .30, posteriores: .10, lombar: .10, abdomen: .05 },
    dicas: [
      'Pés na largura dos ombros, pontas levemente para fora',
      'Joelhos seguem a direção dos pés — não deixe entrar',
      'Respire, trave o abdômen e mantenha o peito aberto',
      'Desça até pelo menos a coxa paralela, calcanhares no chão',
    ],
    vars: [
      { id: 'agachamento', nome: 'Livre (barra)', eq: 'barra' },
      { id: 'agachamento_smith', nome: 'Smith', eq: 'smith', img: 'agachamento_smith', musculos: { quadriceps: .50, gluteos: .30, posteriores: .10, lombar: .10 },
        dica: 'Pés levemente à frente da barra' },
      { id: 'agachamento_goblet', nome: 'Goblet (halter)', eq: 'halteres', img: null },
      { id: 'agachamento_frontal', nome: 'Frontal', eq: 'barra', img: null, musculos: { quadriceps: .60, gluteos: .20, abdomen: .10, lombar: .10 },
        dica: 'Cotovelos altos e tronco mais ereto' },
    ] },
  { id: 'hack', cat: 'Pernas', sub: 'Quadríceps', nome: 'Hack squat', tipo: 'composto', foco: ['gluteo_max'], anim: 'agacha', img: 'hack',
    musculos: { quadriceps: .55, gluteos: .25, posteriores: .20 },
    dicas: [
      'Costas e quadril apoiados no encosto o tempo todo',
      'Pés mais baixos = mais quadríceps; mais altos = mais glúteo',
      'Desça controlando até ~90° ou mais',
      'Não trave os joelhos no topo',
    ],
    vars: [
      { id: 'hack', nome: 'Hack', eq: 'maquina' },
      { id: 'hack_pendulo', nome: 'Pêndulo', eq: 'maquina' },
    ] },
  { id: 'leg_press', cat: 'Pernas', sub: 'Quadríceps', nome: 'Leg press', tipo: 'composto', foco: ['gluteo_max'], anim: 'legpress', img: 'leg_press',
    musculos: { quadriceps: .55, gluteos: .30, posteriores: .15 },
    dicas: [
      'Lombar e quadril colados no encosto — se o quadril descola, diminua a amplitude',
      'Pés na largura dos ombros, joelhos alinhados com os pés',
      'Desça até ~90° no joelho, controlando',
      'Empurre com o pé inteiro e não trave os joelhos no topo',
    ],
    vars: [
      { id: 'leg_press', nome: '45°', eq: 'maquina' },
      { id: 'leg_press_horizontal', nome: 'Horizontal', eq: 'maquina' },
      { id: 'leg_press_uni', nome: 'Unilateral', eq: 'maquina' },
    ] },
  { id: 'extensora', cat: 'Pernas', sub: 'Quadríceps', nome: 'Cadeira extensora', tipo: 'isolado', anim: 'extensora', img: 'extensora',
    musculos: { quadriceps: 1 },
    dicas: [
      'Ajuste o encosto para o joelho ficar alinhado com o eixo da máquina',
      'Rolo apoiado logo acima do tornozelo',
      'Estenda totalmente e segure 1 s no topo',
      'Desça devagar, sem deixar as placas baterem',
    ],
    vars: [
      { id: 'extensora', nome: 'Bilateral', eq: 'maquina' },
      { id: 'extensora_uni', nome: 'Unilateral', eq: 'maquina' },
    ] },
  { id: 'afundo', cat: 'Pernas', sub: 'Quadríceps', nome: 'Afundo / avanço', tipo: 'composto', foco: ['gluteo_max'], anim: 'afundo', img: 'afundo',
    musculos: { quadriceps: .40, gluteos: .40, posteriores: .15, panturrilha: .05 },
    dicas: [
      'Passo longo o bastante para os dois joelhos formarem ~90° embaixo',
      'Tronco ereto e abdômen firme',
      'Joelho da frente alinhado com o pé, sem entrar',
      'Joelho de trás desce em direção ao chão, sem bater',
    ],
    vars: [
      { id: 'afundo', nome: 'Barra', eq: 'barra' },
      { id: 'afundo_halteres', nome: 'Halteres', eq: 'halteres' },
      { id: 'afundo_smith', nome: 'Smith', eq: 'smith' },
      { id: 'afundo_andando', nome: 'Passada (andando)', eq: 'halteres' },
    ] },
  { id: 'bulgaro', cat: 'Pernas', sub: 'Quadríceps', nome: 'Agachamento búlgaro', tipo: 'composto', foco: ['gluteo_max'], anim: 'afundo', img: 'bulgaro',
    musculos: { quadriceps: .40, gluteos: .40, posteriores: .20 },
    dicas: [
      'Pé de trás apoiado no banco, pé da frente bem à frente',
      'Tronco mais inclinado = mais glúteo; mais ereto = mais quadríceps',
      'Desça reto, joelho da frente alinhado ao pé',
      'Peso concentrado na perna da frente',
    ],
    vars: [
      { id: 'bulgaro', nome: 'Barra', eq: 'barra' },
      { id: 'bulgaro_halteres', nome: 'Halteres', eq: 'halteres' },
      { id: 'bulgaro_smith', nome: 'Smith', eq: 'smith' },
    ] },
  { id: 'flexora', cat: 'Pernas', sub: 'Posteriores e glúteos', nome: 'Flexora', tipo: 'isolado', anim: 'flexora', img: 'flexora',
    musculos: { posteriores: .90, panturrilha: .10 },
    dicas: [
      'Joelho alinhado com o eixo da máquina',
      'Quadril colado no banco — não levante o quadril para ajudar',
      'Flexione ao máximo e segure 1 s',
      'Volte devagar até quase estender',
    ],
    vars: [
      { id: 'flexora', nome: 'Mesa (deitado)', eq: 'maquina' },
      { id: 'flexora_sentada', nome: 'Cadeira (sentado)', eq: 'maquina', img: null },
      { id: 'flexora_pe', nome: 'Em pé (unilateral)', eq: 'maquina', img: null },
    ] },
  { id: 'stiff', cat: 'Pernas', sub: 'Posteriores e glúteos', nome: 'Stiff', tipo: 'composto', foco: ['gluteo_max'], anim: 'hinge', img: 'stiff',
    musculos: { posteriores: .50, gluteos: .30, lombar: .20 },
    dicas: [
      'Joelhos levemente dobrados e fixos',
      'Leve o quadril para trás mantendo a coluna neutra',
      'Peso rente às pernas; desça até sentir o posterior alongar',
      'Suba contraindo os glúteos, sem jogar a lombar para trás',
    ],
    vars: [
      { id: 'stiff', nome: 'Barra', eq: 'barra' },
      { id: 'stiff_halteres', nome: 'Halteres', eq: 'halteres' },
      { id: 'stiff_uni', nome: 'Unilateral', eq: 'halteres' },
    ] },
  { id: 'elevacao_pelvica', cat: 'Pernas', sub: 'Posteriores e glúteos', nome: 'Elevação pélvica (hip thrust)', tipo: 'composto', foco: ['gluteo_max'], anim: 'hipthrust', img: 'elevacao_pelvica',
    musculos: { gluteos: .70, posteriores: .25, lombar: .05 },
    dicas: [
      'Parte de baixo das escápulas apoiada no banco',
      'No topo, canelas na vertical — ajuste a distância dos pés',
      'Queixo recolhido e costelas para baixo: suba com o glúteo, não com a lombar',
      'Segure 1–2 s no topo apertando o glúteo',
    ],
    vars: [
      { id: 'elevacao_pelvica', nome: 'Barra', eq: 'barra' },
      { id: 'elevacao_pelvica_maq', nome: 'Máquina', eq: 'maquina', img: null },
      { id: 'elevacao_pelvica_smith', nome: 'Smith', eq: 'smith' },
    ] },
  { id: 'coice', cat: 'Pernas', sub: 'Posteriores e glúteos', nome: 'Glúteo coice', tipo: 'isolado', foco: ['gluteo_max'], faixa: [10, 15],
    musculos: { gluteos: .85, posteriores: .15 },
    dicas: [
      'Abdômen contraído — o movimento é só do quadril',
      'Leve o calcanhar para trás e para cima',
      'Não arqueie a lombar no final',
      'Segure 1 s apertando o glúteo',
    ],
    vars: [
      { id: 'coice_polia', nome: 'Polia', eq: 'polia' },
      { id: 'coice_maquina', nome: 'Máquina', eq: 'maquina' },
      { id: 'coice_4apoios', nome: '4 apoios (caneleira)', eq: 'halteres', inc: 1 },
    ] },
  { id: 'abdutora', cat: 'Pernas', sub: 'Adutores e abdutores', nome: 'Abdução de quadril', tipo: 'isolado', foco: ['gluteo_med'], anim: 'abducao', img: 'abdutora', faixa: [10, 15],
    musculos: { gluteos: 1 },
    dicas: [
      'Tronco apoiado (ou inclinado à frente para mais glúteo)',
      'Abra as pernas controlando, sem embalo',
      'Segure 1 s na abertura máxima',
      'Volte devagar, sem deixar as placas baterem',
    ],
    vars: [
      { id: 'abdutora', nome: 'Cadeira abdutora', eq: 'maquina' },
      { id: 'abdutora_polia', nome: 'Polia (em pé)', eq: 'polia', img: null },
    ] },
  { id: 'adutora', cat: 'Pernas', sub: 'Adutores e abdutores', nome: 'Adução de quadril', tipo: 'isolado', anim: 'aducao', img: 'adutora', faixa: [10, 15],
    musculos: { adutores: 1 },
    dicas: [
      'Comece numa abertura confortável, sem forçar o alongamento',
      'Feche as pernas controlando e segure 1 s',
      'Volte devagar',
    ],
    vars: [
      { id: 'adutora', nome: 'Cadeira adutora', eq: 'maquina' },
      { id: 'adutora_polia', nome: 'Polia (em pé)', eq: 'polia', img: null },
    ] },
  { id: 'panturrilha', cat: 'Pernas', sub: 'Panturrilha', nome: 'Panturrilha', tipo: 'isolado', foco: ['gastro'], anim: 'panturrilha', img: 'panturrilha_pe', faixa: [10, 15],
    musculos: { panturrilha: 1 },
    dicas: [
      'Amplitude total: desça alongando o calcanhar e suba na ponta dos pés',
      'Pausa de 1–2 s embaixo para tirar o efeito "mola"',
      'Sem pressa: ~2 s subindo e 2 s descendo',
    ],
    vars: [
      { id: 'panturrilha_pe', nome: 'Em pé', eq: 'maquina' },
      { id: 'panturrilha_sentado', nome: 'Sentado', foco: ['soleo'], eq: 'maquina', img: 'panturrilha_sentado', dica: 'Joelho dobrado foca mais o sóleo (parte de baixo)' },
      { id: 'panturrilha_legpress', nome: 'No leg press', eq: 'maquina', img: null },
      { id: 'panturrilha_smith', nome: 'Smith / degrau', eq: 'smith' },
    ] },

  // ---------- Core ----------
  { id: 'abdominal', cat: 'Core', nome: 'Abdominal', tipo: 'isolado', foco: ['abd_sup'], desc: 60, anim: 'crunch', img: 'abdominal', faixa: [12, 20],
    musculos: { abdomen: 1 },
    dicas: [
      'Enrole a coluna aproximando as costelas do quadril — não puxe o pescoço',
      'Solte o ar ao subir',
      'Controle a descida',
    ],
    vars: [
      { id: 'abdominal', nome: 'Crunch (solo)', eq: 'corpo' },
      { id: 'abdominal_maq', nome: 'Máquina', eq: 'maquina', img: null },
      { id: 'abdominal_polia', nome: 'Polia (ajoelhado)', foco: ['abd_sup', 'abd_inf'], eq: 'polia', img: null },
    ] },
  { id: 'prancha', cat: 'Core', nome: 'Prancha', tipo: 'isolado', desc: 60, anim: 'prancha', img: 'prancha', seg: true,
    musculos: { abdomen: .70, lombar: .20, ombros: .10 },
    dicas: [
      'Cotovelos embaixo dos ombros',
      'Corpo em linha reta: aperte glúteos e abdômen',
      'Não deixe o quadril cair nem empinar',
      'Respire normalmente',
    ],
    vars: [
      { id: 'prancha', nome: 'Frontal', eq: 'corpo' },
      { id: 'prancha_lateral', nome: 'Lateral', foco: ['obliquos'], eq: 'corpo', img: null, musculos: { abdomen: .80, gluteos: .10, ombros: .10 } },
    ] },
  { id: 'elevacao_pernas', cat: 'Core', nome: 'Elevação de pernas', tipo: 'isolado', foco: ['abd_inf'], desc: 60, anim: 'legraise', img: 'elevacao_pernas', faixa: [10, 20],
    musculos: { abdomen: .90, quadriceps: .10 },
    dicas: [
      'Lombar colada no apoio — se descolar, reduza a amplitude',
      'Suba as pernas sem embalo',
      'Desça devagar',
    ],
    vars: [
      { id: 'elevacao_pernas', nome: 'Deitado', eq: 'corpo' },
      { id: 'elevacao_pernas_barra', nome: 'Na barra (suspenso)', eq: 'corpo', img: null },
      { id: 'elevacao_pernas_paralela', nome: 'Na paralela', eq: 'corpo', img: null },
    ] },
];
